info:
    author: beanyc
    report_version: v1.0
pre_process:
    switch: True
    size:
        col_list: 
            - 6
            - 6
            - 6
            - 6
        half_plate: True
        undistort: 'D:\repos\img_preprocess\preprocess_param\camera_all.pkl'  # 相机正畸文件
        concat: 'D:\repos\img_preprocess\preprocess_param\wg_1121.pkl'        # 分段图拼图文件
    origin_folder: 'D:\repos\img_preprocess\data\1121wg_pwyw\rename'          # 按照WG图序的重命名的原始分段图
img_folder: 'D:\repos\img_preprocess\data\1121wg_pwyw\slice'
output_folder: 'D:\repos\img_preprocess\data\1121wg_pwyw\output'
model:
    safe:
        threshold:
            glass: 0.9
            cell: 0.9
            edge: 0.9
            mid: 0.9
        # model_dir: '/data/wg_train/modeling/detectron2/safedistance/longi_jstz/trains/lgjstz_zj_9bb_dan_half_166_safedistance_210804'
img_type: jpg