info:
    author: beanyc
    report_version: v1.0
pre_process:
    switch: True
    size:
        col_list: 
            - 6
            - 6
            - 6
            - 6
        half_plate: True
        undistort: 'D:\repos\img_preprocess\preprocess_param\camera_all.pkl'
        concat: 'D:\repos\img_preprocess\preprocess_param\wg_0618.pkl'
    origin_folder: 'D:\imgdata\zj\cpdistance\tmp_workspace\temp'
img_folder: 'D:\imgdata\zj\cpdistance\tmp_workspace\data_cut'
output_folder: 'D:\imgdata\zj\cpdistance\tmp_workspace\output'
model:
    safe:
        threshold:
            glass: 0.9
            cell: 0.9
            edge: 0.9
            mid: 0.9
        # model_dir: '/data/wg_train/modeling/detectron2/safedistance/longi_jstz/trains/lgjstz_zj_9bb_dan_half_166_safedistance_210804'
img_type: jpg